name: Build and Collect Logs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-log:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare logs directory
        run: |
          mkdir -p logs
          sudo chmod 777 logs

      - name: Build and run Docker
        run: |
          docker build -t logger .
          docker run --rm -v "$(pwd)/logs:/home/logs" logger || echo "Container executed"

      - name: Verify logs
        run: |
          echo "=== LOG FILES ==="
          ls -la logs/
          echo -e "\n=== BUILD LOG ==="
          cat logs/build.log
          echo -e "\n=== APP LOG ==="
          cat logs/log.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: logs/
          retention-days: 7
