name: Build and Run in Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-run-docker:
    runs-on: ubuntu-latest
    name: Build Docker image and run build inside container

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t logger .
          docker images

      - name: Create logs directory and run container
        run: |
          mkdir -p logs
          docker run --rm -v "$(pwd)/logs:/home/logs" logger || echo "Container executed"

      - name: Verify log file
        run: |
          ls -la logs/  # Для отладки
          if [ -f "logs/log.txt" ]; then
            echo "=== LOG CONTENT ==="
            cat logs/log.txt
            echo "==================="
          else
            echo "Error: Log file not found!" >&2
            exit 1
          fi

      - name: Upload log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: logs/log.txt
          retention-days: 3
