name: Build and Collect Logs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-log:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          mkdir -p logs
          sudo chmod -R 777 logs 

      - name: Build Docker image
        run: docker build -t logger .

      - name: Run container and get logs
        run: |
          docker run --rm -v "$(pwd)/logs:/home/logs" logger || echo "Container executed"
          sudo chmod -R 755 logs  

      - name: Verify logs
        run: |
          ls -la logs/
          [ -f "logs/log.txt" ] && echo "Log content:" && cat logs/log.txt || echo "No log file found"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: logs/
          retention-days: 7
