name: Build and Collect Logs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-log:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t logger .
          mkdir -p logs
          
      - name: Run container and get logs
        run: |
          docker run --rm -v "$(pwd)/logs:/home/logs" logger || echo "Container executed"
          
          
          touch logs/build.log logs/log.txt

      - name: Prepare combined log
        run: |
          echo "=== SYSTEM INFO ===" > combined.log
          echo "Date: $(date)" >> combined.log
          echo "CPU: $(nproc) cores" >> combined.log
          
          echo -e "\n=== BUILD LOG ===" >> combined.log
          [ -f "logs/build.log" ] && cat logs/build.log >> combined.log || echo "Build log not found" >> combined.log
          
          echo -e "\n=== APP LOG ===" >> combined.log
          [ -f "logs/log.txt" ] && cat logs/log.txt >> combined.log || echo "App log not found" >> combined.log
          
          echo -e "\n=== BUILD ARTIFACTS ===" >> combined.log
          ls -R build/ >> combined.log 2>&1 || echo "No build directory" >> combined.log

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            combined.log
            logs/build.log
            logs/log.txt
          retention-days: 7
