name: Build in Docker and upload log

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t logger .
          docker images

      - name: Run container and extract logs
        run: |
          mkdir -p logs
          docker run --rm -v "$(pwd)/logs:/home/logs" logger
          cat logs/log.txt

      - name: Upload log file
        uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: logs/log.txt
