name: Build and Collect Logs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-log:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t logger .

      - name: Run Docker container and extract logs
        run: |
          mkdir -p logs
          docker run --rm -v "$(pwd)/logs:/home/logs" logger

          
          docker create --name temp_container logger
          docker cp temp_container:/app/logs ./logs_from_container
          docker rm temp_container

      - name: Save combined log
        run: |
          echo "=== BUILD LOG ===" > combined.log
          cat ./logs_from_container/build.log >> combined.log

          echo -e "\n=== APP LOG ===" >> combined.log
          cat ./logs_from_container/app_run.txt >> combined.log

          echo -e "\n=== DIR STRUCTURE ===" >> combined.log
          ls -R build >> combined.log

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            combined.log
            logs_from_container/
          retention-days: 7
