name: Build and Collect Logs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t logger .

      - name: Create logs directory and run container
        run: |
          mkdir -p logs
          docker run --rm -v "$(pwd)/logs:/home/logs" logger
          ls -la logs/  # Проверяем, что файлы созданы

      - name: Prepare combined log
        run: |
          echo "=== SYSTEM INFO ===" > combined.log
          echo "Date: $(date)" >> combined.log
          echo "CPU: $(nproc) cores" >> combined.log

          echo -e "\n=== BUILD LOG ===" >> combined.log
          cat logs/build.log >> combined.log 2>/dev/null || echo "Build log not found" >> combined.log

          echo -e "\n=== APP LOG ===" >> combined.log
          cat logs/app_run.log >> combined.log 2>/dev/null || echo "App log not found" >> combined.log

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            combined.log
            logs/
          retention-days: 7
