name: Build project in Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image
        run: |
          docker build -t logger .
          docker images

      - name: Run container to generate artifacts
        run: |
          mkdir -p logs
          docker run --rm -v "$(pwd)/logs:/home/logs" logger
          cat logs/log.txt || echo "No log file generated"

      - name: Upload log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: logs/log.txt
          retention-days: 3
