name: Build and Collect Logs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-log:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare logs directory
        run: |
          mkdir -p logs
          chmod -R 777 logs

      - name: Build Docker image
        run: docker build -t logger .

      - name: Run container to build project
        run: |
          docker run --rm -v "$(pwd)/logs:/home/logs" logger
          ls -la logs/

      - name: Verify logs
        run: |
          echo "=== BUILD LOG ==="
          cat logs/build.log || echo "No build log found"

          echo -e "\n=== APP RUN LOG ==="
          cat logs/app_run.log || echo "No app log found"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            logs/build.log
            logs/app_run.log
          retention-days: 7
