name: Build and Collect Logs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-log:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run Docker
        run: |
          docker build -t logger . 
          mkdir -p logs
          docker run --rm -v "$(pwd)/logs:/home/logs" logger

      - name: Save build logs
        run: |
          echo "=== BUILD LOG ===" > combined.log
          cat logs/build.log >> combined.log
          echo -e "\n=== APP LOG ===" >> combined.log
          cat logs/log.txt >> combined.log
          echo -e "\n=== DIR STRUCTURE ===" >> combined.log
          ls -R build >> combined.log

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            combined.log
            logs/build.log
            logs/log.txt
          retention-days: 7
