name: Build and Collect Logs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-log:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t logger .

      - name: Create logs directory and run container
        run: |
          mkdir -p logs
          docker run --rm -v "$(pwd)/logs:/home/logs" logger
          ls -la logs/  # Проверяем, что файлы созданы

      - name: Prepare combined log
        run: |
          echo "=== BUILD LOG ===" > combined.log
          cat logs/build.log >> combined.log

          echo -e "\n=== APP LOG ===" >> combined.log
          cat logs/log.txt >> combined.log

          echo -e "\n=== APP RUN LOG ===" >> combined.log
          cat logs/app_run.log >> combined.log

          echo -e "\n=== DIR STRUCTURE ===" >> combined.log
          ls -R build >> combined.log

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            logs/
            combined.log
          retention-days: 7
